elevations/elevations/urls.py
from django.contrib import admin
from django.urls import path,include
from .settings import MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static
from home.views import home_view,register_form,login_view,logout_action
from django.views.generic import TemplateView
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_action, name='logout'),
    path('register/', register_form, name='register'),
    path('', home_view,name='home'),
    path('survey/', include('survey_notebook.urls')),


] + static(MEDIA_URL, document_root=MEDIA_ROOT)

elevations/survey_notebook/urls.py
from django.urls import path
from .views import add_record_view, survey_home_view, view_survey_record_view, \
    handle_actions, update_survey_form_view, manage_survey_images_view, \
    delete_survey_images

urlpatterns = [
    path('', survey_home_view, name='survey_home_view'),
    path('add/', add_record_view, name='add_record_view'),
    path('view/', view_survey_record_view, name='view_survey_record_view'),
    path('action/', handle_actions, name='handle_actions'),
    path('delete/<int:id>', delete_survey_images, name='delete_survey_images'),
    path('update/<int:id>', update_survey_form_view, name='update_survey_form_view'),
    path('images/<int:id>', manage_survey_images_view, name='manage_survey_images_view'),

    # path('update/<int:id>', update_workout_form_view, name='update_workout_form_view'),

]

elevations/survey_notebook/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


def user_directory_path(instance, filename):
    # instance of Survey_images model
    # file will be uploaded to MEDIA_ROOT / userid/<filename>
    return 'Survey/{0}/{1}'.format(instance.note_id.user_id, filename)




class Survey_Notebook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=User)
    Identification = models.CharField(max_length=50, null=True, blank=True,default=None)  # foundations/structures names
    notes = models.CharField(max_length=500, null=True, blank=True,default=None)  # general notes
    date = models.DateField(default=timezone.now(), null=True)
    BenchMark = models.FloatField(null=True, blank=True,default=None)
    Shot = models.FloatField(null=True, blank=True,default=None)
    HI = models.FloatField(null=True, blank=True,default=None)

    style_class={}

    def __str__(self):
        return f'{self.user}:{self.pk}'

    def validate_record(self):
        solved_fields = []
        # related fields [ 'BenchMark', 'Shot', 'HI', 'Target', 'EL', 'RR']
        # handle benchmark,Shot,HI logic
        #SOLVE FOR HI
        if self.BenchMark and self.Shot and not self.HI:
            self.HI = self.BenchMark + self.Shot
            # self.style_class['HI'] = 'solved'
            if self.pk in self.style_class.keys():
                old: dict = self.style_class[self.pk]
                old.update({'HI': 'solved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'HI': 'solved'}
        else:
            # self.style_class['HI'] = 'unsolved'
            if self.pk in self.style_class.keys():
                old: dict = self.style_class[self.pk]
                old.update({'HI': 'unsolved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'HI': 'unsolved'}

        # solve for Shot
        if self.BenchMark and self.HI and not self.Shot:
            self.Shot = self.HI - self.BenchMark
            # self.style_class['Shot'] = 'solved'
            if self.pk in self.style_class.keys():
                old: dict = self.style_class[self.pk]
                old.update({'Shot': 'solved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'Shot': 'solved'}
        else:
            # self.style_class['Shot'] = 'unsolved'
            if self.pk in self.style_class.keys():
                old: dict = self.style_class[self.pk]
                old.update({'Shot': 'unsolved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'Shot': 'unsolved'}


        if self.Shot and self.HI and not self.BenchMark:
            self.BenchMark = self.HI - self.Shot
            # self.style_class['BenchMark'] = 'solved'
            if self.pk in self.style_class.keys():
                old: dict = self.style_class[self.pk]
                old.update({'BenchMark': 'solved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'BenchMark': 'solved'}
        else:
            # self.style_class['BenchMark'] = 'unsolved'
            if self.pk in self.style_class.keys():
                old: dict = self.style_class[self.pk]
                old.update({'BenchMark': 'unsolved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'BenchMark': 'unsolved'}
    def get_class(self):
      return self.style_class[self.pk]


class Survey_elevations(models.Model):
    elevation_id = models.ForeignKey(Survey_Notebook, on_delete=models.CASCADE, default=Survey_Notebook)
    name = models.CharField(max_length=50, null=True, blank=True, default=None)  # label ex: TOC,TOB,TOF
    EL = models.FloatField(max_length=6,null=True, blank=True, default=None)
    RR = models.FloatField(max_length=6,null=True, blank=True, default=None)
    HI = None
    style_class = {}
    def __str__(self):
        return f'EL {self.pk} from {self.elevation_id}'

    def validate_record(self):
        solved_fields = []
        # related fields [ 'BenchMark', 'Shot', 'HI', 'Target', 'EL', 'RR']
        # handle benchmark,Shot,HI logic
        if self.EL and self.HI and not self.RR:
            self.RR = round(self.HI - self.EL,2)
            # self.style_class['RR'] = 'solved'
            if self.pk in self.style_class.keys():
                old:dict = self.style_class[self.pk]
                old.update({'RR':'solved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'RR':'solved'}

        else:
            # self.style_class['RR'] = 'unsolved'
            if self.pk in self.style_class.keys():
                old:dict = self.style_class[self.pk]
                old.update({'RR':'unsolved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'RR':'unsolved'}

        if self.RR and self.HI and not self.EL:
            self.EL = round(self.HI - self.RR,2)
            # self.style_class['RR'] = 'solved'
            if self.pk in self.style_class.keys():
                old:dict = self.style_class[self.pk]
                old.update({'EL':'solved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'EL':'solved'}

        else:
            # self.style_class['RR'] = 'unsolved'
            if self.pk in self.style_class.keys():
                old:dict = self.style_class[self.pk]
                old.update({'EL':'unsolved'})
                self.style_class[self.pk] = old
            else:
                self.style_class[self.pk] = {'EL':'unsolved'}




        return self.style_class
    def get_class(self):
      return self.style_class[self.pk]


class Survey_images(models.Model):
    note_id = models.ForeignKey(Survey_Notebook, on_delete=models.CASCADE,default=Survey_Notebook)
    image = models.ImageField(default="no-image.jpg", upload_to=user_directory_path, null=True, blank=True)



# Create your models here.

elevations/survey_notebook/views.py
import datetime

import django.utils.timezone
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Survey_Notebook, Survey_images, Survey_elevations
from .forms import CreateSurveyNote, CreateSurveyImages_form, CreateSurveyElevations
from django.urls import reverse
import json


# TODO: edit records,make view look good. add date field
# error in template because image dont have a default image to display
def survey_home_view(request, *args, **kwargs):
    return render(request, 'survey_home.html', {})


def handle_actions(request, *args, **kwargs):
    if request.GET:
        print(request.GET)
        if 'delete' in request.GET:
            d = Survey_Notebook.objects.get(user=request.user, pk=request.GET['delete'])
            d.delete()
            return view_survey_record_view(request)
        elif 'template' in request.GET:
            w = Survey_Notebook.objects.get(pk=request.GET['template'])
            form = CreateSurveyNote(instance=w)
            return render(request, 'add_record.html', {"form": form})
        elif 'edit' in request.GET:
            return redirect('update_survey_form_view', id=request.GET['edit'])
        elif 'images' in request.GET:
            node_id = request.GET['images']
            return manage_survey_images_view(request, id=node_id)
            # return redirect('manage_survey_images_view', id=node_id)
        else:
            return view_survey_record_view(request)


def update_survey_form_view(request, id, *args, **kwargs):
    w = Survey_Notebook.objects.get(pk=id)
    form = CreateSurveyNote(instance=w)
    els_forms = []
    elevations = Survey_elevations.objects.filter(elevation_id=id)
    for e in elevations:
        print(f'loading pk{e.pk}| name:{e.name} EL:{e.EL} RR:{e.RR}')
        e_form = CreateSurveyElevations(instance=e)
        els_forms.append([e_form, e.pk])

    if request.POST:
        print(request.POST)
        w = Survey_Notebook.objects.get(pk=id)
        form = CreateSurveyNote(request.POST, instance=w)

        if 'pk' in request.POST:
            pks: list = request.POST.getlist('pk')
            names = request.POST.getlist('name')
            rrs = request.POST.getlist('RR')
            els = request.POST.getlist('EL')
            zipped = zip(pks, names, rrs, els,range(len(pks)))
            toBePopped = []
            toBeAdded = []
            for pk, name, rr, el,index in zipped:
                print(f'start index {index}')
                print(pks)
                if pk == 'new':
                    if rr == '' and el == '' and name == '':  # skips empty records
                        toBePopped.append(index)
                        print(f'skipping index{index} name:{name}')
                        continue

                    else:
                        if rr == '':
                            rr = None
                        if el == '':
                            el = None
                    elevations = Survey_Notebook
                    elevation = elevations.objects.get(pk=id)
                    new = elevation.survey_elevations_set.create(name=name, EL=el, RR=rr)
                    print(f'new elevation added to Note {id}, {new.pk}')
                    toBePopped.append(index)
                    print(f'popping index{index} name:{name} pk:{pk}')
                    toBeAdded.append(new.pk)
                    continue

                elevation = Survey_elevations.objects.get(pk=pk)
                e_form = CreateSurveyElevations(instance=elevation)
                uform = e_form.save(commit=False)
                uform.name = name
                if rr != '':
                    uform.RR = float(rr)
                else:
                    uform.RR = None

                if el != '':
                    uform.EL = float(el)
                else:
                    uform.EL = None
                uform.save()
                print(f'elevation ({pk}) updated ')
            #remove all indexes with 'new' from pks
            for i in sorted(toBePopped, reverse=True):
                pks.pop(i)
                # we reverse the order of indexes to avoid
                # IndexError: pop index out of range:
                # you can pop indexes 9,7,5,3 (decreasing order)
                # but not 3,5,7,9
                # by the time we pop the first 3 indexes the list would be lenght of 6
                # and we would try to pop 9 that no longer exist

            pks.extend(toBeAdded) # add newly created pk's to pks list
            #we delete all elevations not found on pks list
            rows_to_delete = Survey_elevations.objects.exclude(pk__in=pks)
            rows_to_delete.all().delete()
        if form.is_valid():
            # f = form.save(commit=False)
            # f.user = request.user
            form.save()
            # return view_survey_record_view(request)
            return HttpResponseRedirect(reverse('view_survey_record_view'))
        else:
            return render(request, 'update_record.html', {"form": form, "id": id, "els_forms": els_forms})
    return render(request, 'update_record.html', {"form": form, "id": id, "els_forms": els_forms})


def manage_survey_images_view(request, id, *args, **kwargs):
    form = CreateSurveyImages_form(initial={'note_id': id})
    context = {'form': form}
    if request.POST:
        if 'delete' in request.POST:
            d = Survey_images.objects.get(pk=request.POST['delete'])
            d.delete()
        else:
            form = CreateSurveyImages_form(request.POST, request.FILES)
            print('saving image')
            context = {'form': form}
            if form.is_valid():
                f = form.save(commit=False)
                sn = Survey_Notebook.objects.get(pk=id)
                f.note_id = sn
                f.save()
                context['message'] = "image created"
                return HttpResponseRedirect(reverse('manage_survey_images_view',args=[id]))
    else:
        print('not POST')
    img_queryset = Survey_images.objects.filter(note_id=id)

    context['images'] = img_queryset
    context['id'] = id

    return render(request, 'survey_manage_images.html', context)



def delete_survey_images(request, id, *args, **kwargs):
    d = Survey_images.objects.get(pk=id)
    d.delete()
    return manage_survey_images_view(request)


def view_survey_record_view(request, *args, **kwargs):
    records = list(Survey_Notebook.objects.filter(user=request.user).reverse())
    records.reverse()
    data = []
    message = ""
    dev = ""
    if len(records) == 0:
        message = ("no records yet", "warning")
    else:  # we have records, lets extract the image urls

        for record in records:
            images = []
            elevations = []
            record.validate_record()
            for img in record.survey_images_set.all():  # iterate image model inside Survey_Notebook
                images.append(img.image.url)
                # print(img.image.url)
            if len(images) == 0:
                images.append("/media/no-image.jpg")
            for e in record.survey_elevations_set.all():  # iterate image model inside Survey_Notebook
                e.HI = record.HI
                e.validate_record()
                #todo: validation working right, but not outputting class properly
                elevations.append(e)


            data.append([record, images, elevations])  # gather queryset,images,elevations

        style_class = records[-1].style_class
        style_class = json.dumps(style_class,indent=4)
        dev = (f'style_class:\n' \
               f'{style_class}\n' \
               f'All:\n' \
               f'images:\n ' \
               f'{images}',
               "textarea")
    context = {"records": records,
               "message": message,
               "dev": dev,
               "data": data}
    return render(request, 'view_records.html', context)


def add_record_view(request, *args, **kwargs):
    print(f'request:\n\n{request.POST}\n\nend request')
    # todo: default date stop working, template not getting filled.
    form = CreateSurveyNote(request.POST, initial={"user": request.user, "date": django.utils.timezone.now()})
    form1 = CreateSurveyElevations()

    # Two changes are required to save images, 1 is pass request.FILES to form
    # and 2 set enctype='multipart/form-data' inside <form> tag in used template
    if request.POST:
        form = CreateSurveyNote(request.POST, request.FILES, initial={"user": request.user})
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            pk = f.pk
            print(f'pk={pk}')
            if 'name' in request.POST:
                names = request.POST.getlist('name')
                rrs = request.POST.getlist('RR')
                els = request.POST.getlist('EL')
                zipped = zip(names, rrs, els)
                print(names)
                for name, rr, el in zipped:
                    if rr == '' and el == '' and name == '':  # skips empty records
                        print(f'skipping record')
                        continue

                    else:
                        if rr == '':
                            rr = None
                        if el == '':
                            el = None
                        elevations = Survey_Notebook
                        elevation = elevations.objects.get(pk=pk)
                        print(f'record={elevation}')
                        print(f'record={dir(elevation.survey_elevations_set)}')
                        elevation.survey_elevations_set.create(name=name, EL=el, RR=rr)
                        print(f'new elevation added to Note{pk}')

            else:
                print('no names')

            return HttpResponseRedirect(reverse('view_survey_record_view'))

elevations/survey_notebook/templates/add_record.html
{% extends 'survey.html' %}
{% block survey %}
<p></p>
<script>
function addRow (top) {
  var table = document.getElementById("demoA");
  if (top) { var row = table.insertRow(0); }
  else { var row = table.insertRow(); }

  // (B3) INSERT CELLS
  var cell = row.insertCell();
  cell.innerHTML = `
  <div>name:{{form1.name}}
  EL:{{form1.EL}}RR:{{form1.RR}}
  <input type="button" value="Delete" onclick="deleteRow(this)"></div>

  `;
}
function deleteRow(r) {
  var i = r.parentNode.parentNode.rowIndex;
  document.getElementById("demoA").deleteRow(i);
}
</script>
<form method="post" action="{% url 'add_record_view' %}" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
    {{form.as_table}}
    <tr>
        <td>
            <input type="button" value="Add EL Bottom" onclick="addRow()"/>
        </td>
        <td>
            <input type="button" value="Add EL Top" onclick="addRow(1)"/>
        </td>

    </tr>
    </table>
    <table id="demoA">

    </table>
    <input type="submit" name="Save">
</form>
{% endblock %}

elevations/survey_notebook/templates/image_widget_carousel.html
<div class="card" >
    {# we must pass forloop.counter into id in order to generate different carousel ids #}
        <div id="carousel{{forloop.counter}}" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                  {% for image in images %}
                  {% if forloop.first %}
                <div class="carousel-item active">
                  <img src="{{image}}" class="img-thumbnail  d-block w-100 h-100 myImg" alt="{{image}}" s>
                </div>
                  {% else %}
                  <div class="carousel-item">
                  <img src="{{image}}" class="img-thumbnail  d-block w-100 h-100 myImg" alt="{{image}}" >
                </div>
                  {% endif %}
                {% endfor %}
  </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel{{forloop.counter}}" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel{{forloop.counter}}" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>

elevations/survey_notebook/templates/survey-navbar-menu.html
        <li class="nav-item"> <a class="nav-link" href="{% url 'survey_home_view' %}">Survey-NB</a></li>
        <li> <a class="nav-link" href="{% url 'add_record_view' %}">Add record</a></li>
         <li> <a class="nav-link" href="{% url 'view_survey_record_view' %}">View My Records</a></li>

elevations/survey_notebook/templates/survey.html
{% extends 'base.html' %}
{% block body %}

{% include 'header.html' %}
{% block survey %}
{% endblock %}
{% endblock %}

elevations/survey_notebook/templates/survey_home.html
{% extends 'survey.html' %}
{% block survey %}
this is home survey
{% endblock %}

elevations/survey_notebook/templates/survey_manage_images.html
{% extends 'survey.html' %}
{% block survey %}
<p></p>
{{message}}
<style>

    .row {
  display: flex;
  flex-wrap: wrap;
  padding: 0 4px;
}

/* Create four equal columns that sits next to each other */
.column {
  flex: 25%;
  max-width: 25%;
  padding: 0 4px;
}

.column .card {
  margin-top: 8px;
  vertical-align: middle;
  horizontal-align: middle;
  width: 100%;
  max-width:350px;
}

/* Responsive layout - makes a two column-layout instead of four columns */
@media screen and (max-width: 800px) {
  .column {
    flex: 50%;
    max-width: 50%;
  }
}

/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column {
    flex: 100%;
    max-width: 100%;
  }
}
</style>
<form method="post" action="{% url 'manage_survey_images_view' id %}" enctype="multipart/form-data">
      {% csrf_token %}
{{form.as_p}}

    <input type="submit" name="Save">
</form>
<p></p>
<form METHOD="post" action="{% url 'manage_survey_images_view' id %}" enctype='multipart/form-data'>
{% csrf_token %}
    <input type="hidden" name="note_id" value="{{note_id}}">

{% for image in images %}

<div class="row">
    <div class="column">
        <div class="card bg-dark text-white text-end" id="mycard">
          <img src="{{image.image.url}}" class="card-img" alt="...">
          <div class="card-img-overlay">
              <button type="submit" name="delete" value="{{image.pk}}" onclick="return confirm('Are you sure you want to delete it?');">delete</button>
          </div>
        </div>
    </div>
</div>
{% endfor %}

</form>
{% endblock %}

elevations/survey_notebook/templates/update_record.html
{% extends 'survey.html' %}
{% block survey %}
<p></p>
<script>
function addRow (top) {
  var table = document.getElementById("demoA");
  if (top) { var row = table.insertRow(0); }
  else { var row = table.insertRow(); }

  var cell = row.insertCell();
  cell.innerHTML = `
  <div>name:<input type="text" name="name" style="width:70px" maxlength="50" id="id_name">
  EL:<input type="number" name="EL" style="width:70px" step="any" id="id_EL">RR:<input type="number" name="RR" style="width:70px" step="any" id="id_RR">
   <input type="hidden" name="pk" value="new"/>
  <input type="button" value="Delete" onclick="deleteRow(this)"></div>

  `;
}
function deleteRow(r) {
  var i = r.parentNode.parentNode.rowIndex;

  if(confirm('Elevations get deleted for good when the operation is saved.\n You can refresh the page to restore any information not saved')) {
  document.getElementById("demoA").deleteRow(i);
  }
}
</script>
<form method="post" action="{% url 'update_survey_form_view' id %}" enctype='multipart/form-data' onsubmit="return confirm('are you sure?');">
    {% csrf_token %}
{{form.as_p}}
    <table>
        <tr>
        <td>
            <!-- "addRow(1) to add to the top of table -->
            <input type="button" value="Add EL" onclick="addRow(1)"/>
        </td>


    </tr>
    </table>
    <table id="demoA">
    <input type="submit" name="Save">
    {% for el_form in els_forms %}
        <tr>
            <td>
                name:{{el_form.0.name}}
                EL:{{el_form.0.EL}}RR:{{el_form.0.RR}}
                <input type="button" value="Delete" onclick="deleteRow(this)">
                <input type="hidden" name="pk" value="{{el_form.1}}"/>PK:{{el_form.1}}
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

elevations/survey_notebook/templates/view_records.html
{% extends 'survey.html' %}
{% block survey %}

<style>
table {
border-radius:10px;
  min-width:400px;


}
table, th, td {
  background-color: #0d6efd;
border: 0px solid;
}
.bench_group {
    background-color: #2c7f98;
}
.bench_group:hover {background-color: coral;}
.target_group:hover {background-color: coral;}
.target_group {
    background-color: #619fb2;
}
.notes {
    text-align:center;
}
.date{
    text-align:left;
}
.image_td {
    text-align:center;
    min-width:50x;
    max-width:60px;
}
.labels1 {
    text-align:left;
    width:100px;


}
.img-thumbnail {
margin:auto
    width: auto;
    max-width: 432px;
    height: 225px;
    min-height: 225px;
    max-height: 225px;
}
.solved {
background-color:#13ff2a;
animation: blinkingBackground 2s infinite;
}
.unsolved {
background-color:yellow;
}
@keyframes blinkingBackground{
		0%		{ background-color: #13ff2a;}
		25%		{ background-color: #13ff2a;}
		50%		{ background-color: #13ff2a;}
		75%		{ background-color: #13ff2a;}
		100%	        { background-color: #0d6efd;}
	}

</style>

<style>
    /* Style the Image Used to Trigger the Modal */
#myImg {
  border-radius: 5px;
  cursor: pointer;
  transition: 0.3s;
}

#myImg:hover {opacity: 0.7;}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Modal Content (Image) */
.modal-content {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
}

/* Caption of Modal Image (Image Text) - Same Width as the Image */
#caption {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
  text-align: center;
  color: #ccc;
  padding: 10px 0;
  height: 150px;
}

/* Add Animation - Zoom in the Modal */
.modal-content, #caption {
  animation-name: zoom;
  animation-duration: 0.6s;
}

@keyframes zoom {
  from {transform:scale(0)}
  to {transform:scale(1)}
}

/* The Close Button */
.close {
  position: absolute;
  top: 15px;
  right: 35px;
  color: #f1f1f1;
  font-size: 40px;
  font-weight: bold;
  transition: 0.3s;
}

.close:hover,
.close:focus {
  color: #bbb;
  text-decoration: none;
  cursor: pointer;
}

/* 100% Image Width on Smaller Screens */
@media only screen and (max-width: 700px){
  .modal-content {
    width: 100%;
  }
}
</style>
<center>
<script>
    function deleteRecord(r) {
  if(confirm('Elevations get deleted for good when the operation is saved.\n You can refresh the page to restore any information not saved')) {
    return true;
  }
}
</script>
<p></p>
{#['user','Identification','image','notes','date','BenchMark','Shot','HI','Target','EL','RR']#}
<form action="{% url 'handle_actions' %}">

{% for line in data %}
    {% with record=line.0 images=line.1 elevations=line.2 %}
    {{record.solved_fields}}

    <table>
        <tr><td colspan="4" class="image_td"> {% include 'image_widget_carousel.html' %}</td></tr>
    <tr><th class="labels1" >Identification:</th>
        <td class="labels1">{{record.Identification}}</td>
        <td rowspan="2" colspan="2" class="image_td">
        </td></tr>
        <tr><th class="labels1">Date:</th><td class="date" >{{record.date}}</td></tr>
    <tr><th colspan="4" class="notes">Notes:</th></tr>
    <tr>
        <td colspan="4" class="notes"><textarea disabled name="Text1" cols="35" rows="3">{{record.notes}}</textarea></td>
    </tr>
     <tr>
         <th class="bench_group">BenchMark:</th>
         <td class="bench_group {{record.get_class.BenchMark}}">{{record.BenchMark}}</td>
     </tr>
     <tr>
         <th class="bench_group ">Shot:</th>
         <td class="bench_group {{record.get_class.Shot}}">{{record.Shot}}</td>
     </tr>
     <tr>
         <th class="bench_group">HI:</th><td class="bench_group {{record.get_class.HI}}">{{record.HI}}</td>
     </tr>
        {% if elevations %}
    <tr>
        <th style="text-align: center;" colspan="3">ELEVATIONS</th>
    </tr>
         <tr>
        <th>NAME</th>
             <th>EL</th>
             <th>RR</th>
    </tr>
        {% endif %}
        {% for elevation in elevations %}
        <tr>
            <th>{{elevation.name}}</th>
            <td class="{{elevation.get_class.EL}}">{{elevation.EL}}</td>
            <td class="{{elevation.get_class.RR}}">{{elevation.RR}}</td>
        </tr>
        {% endfor %}
     <tr>
            <td class="text-align:center;" colspan="4">
                <button type="submit" name="delete" value="{{record.pk}}" onclick="return confirm('Are you sure you want to delete it? ?');">DELETE</button>
                <button type="submit" name="edit" value="{{record.pk}}">edit</button>
                <button type="submit" name="template" value="{{record.pk}}">Use as template</button>
                <button type="submit" name="images" value="{{record.pk}}">Manage Pictures</button>
            </td>

     </tr>
</table>
    <p></p>
    {%endwith %}
{% endfor %}
</form>
</center>
<!-- The Modal -->
<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>
<script>
var modal = document.getElementById("myModal");
var i;

var img = document.getElementsByClassName("myImg");
var modalImg = document.getElementById("img01");

 for(i=0;i< img.length;i++)
   {
    img[i].onclick = function(){

    modal.style.display = "block";
       modalImg.src = this.src;

 }
}

var span = document.getElementsByClassName("close")[0];


span.onclick = function() {
   modal.style.display = "none";
}
</script>
{% endblock %}